bump(main/salty-chat): 0.0.22-p20251006
- For some reason, the release archive URL does not work anymore, but downloading the release tag using the git protocol does work.

- However, for some reason the current release fails to build in termux-packages GitHub Actions with error ` ../../_cache/go1.25.0-r1/src/os/user/lookup.go:22:41: undefined: current`, but not locally, but the current master branch is not affected by that error, so bump to the newest commit.