bump(main/gexiv2): 0.14.3
* Remove unused -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES compiler flag
  which was added in 3157a78171fa755e31ed8f776f5b4ad0110c64f8 commit.

* Fix the following build error.
  OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/usr/bin/glib-mkenums'